builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
    main: ./gm.go
    ldflags:
     - -s -w -X 'main.gmVersion={{.Version}}' -X 'main.gmBuildCommit={{.Commit}}' -X 'main.gmBuildTimestamp={{.Date}}'
archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
      - goos: darwin
        format: zip
checksum:
  name_template: "checksums.txt"
  algorithm: sha512
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - Merge pull request
      - Merge branch
signs:
  - artifacts: all
    args: ["--batch", "-u", "{{ .Env.GPG_FINGERPRINT }}", "--output", "${signature}",  "--detach-sign",  "${artifact}"]
snapcrafts:
  - name: gum
    grade: stable
    confinement: strict
    publish: true
    summary: "Gum is a Gradle/Maven/jbang wrapper written in Go"
    description: |
      Gum is a Gradle/Maven/jbang wrapper written in Go, inspired in https://github.com/dougborg/gdub and https://github.com/srs/gw.
      Gum automatically detects if the project is Gradle, Maven, or jbang based and runs the appropriate command. However in the case
      that Gum guesses wrong you can force a specific build tool to be used. Similarly as gdub, Gum lets you invoke either Gradle or 
      Maven from anywhere within the project structure, not just the root directory.

      **Usage**

      Gum supports the following flags

      * **-gd** displays debug information
      * **-gg** force Gradle build
      * **-gh** displays help information
      * **-gj** force jbang execution
      * **-gm** force Maven build
      * **-gn** executes nearest build file
      * **-gq** run gm in quiet mode
      * **-gr** do not replace goals/tasks
      * **-gv** displays version information

      Gum will execute the build based on the root build file unless **-gn** is specified, in which case the nearest build file
      will be selected. If a specific build file is given (**-b**, **--build-file** for Gradle; **-f**, **--file** for Maven)
      then that file will be used instead.
brews:
  - name: gum
    goarm: 6
    github:
      owner: kordamp
      name: gum-homebrew-tap
    folder: Formula
    homepage: "https://github.com/kordamp/gm"
    description: "Gum is a Gradle/Maven/jbang wrapper written in Go"
    skip_upload: false
