name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      CI: true
      GOPATH: ${{ github.workspace }}
      GO111MODULE: off
    steps:
      - uses: actions/checkout@v1
        with:
          path: ./src/github.com/${{ github.repository }}
      - uses: actions/setup-go@v1
        with:
          go-version: '1.14.3'
      - run: go build gm.go
